language: php

before_install:
  # If PHP >= 5.6, download & install PHPunit 5.7 to avoid builds failures
  - if php -r "exit( (int)! version_compare( '$TRAVIS_PHP_VERSION', '5.6', '>=' ) );"; then wget -O phpunit https://phar.phpunit.de/phpunit-5.7.phar && chmod +x phpunit && mkdir ~/bin && mv -v phpunit ~/bin; fi

php:
  - '5.6'
 
before_script:
  - composer install

script: phpunit --configuration phpunit.xml
